In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

print("✅ All imports working")

✅ All imports working

In [3]:
jobs = pd.read_csv("../data/raw/postings.csv")

print(f"Total rows: {jobs.shape[0]}")
print(f"Total columns: {jobs.shape[1]}")
print("\nColumn names:")
print(jobs.columns.tolist())

Total rows: 123849
Total columns: 31

Column names:
['job_id', 'company_name', 'title', 'description', 'max_salary', 'pay_period', 'location', 'company_id', 'views', 'med_salary', 'min_salary', 'formatted_work_type', 'applies', 'original_listed_time', 'remote_allowed', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'normalized_salary', 'zip_code', 'fips']

In [4]:
jobs.head(3)

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0

In [5]:
print("Missing values per column:")
print(jobs.isnull().sum())

Missing values per column:
job_id                             0
company_name                    1719
title                              0
description                        7
max_salary                     94056
pay_period                     87776
location                           0
company_id                      1717
views                           1689
med_salary                    117569
min_salary                     94056
formatted_work_type                0
applies                       100529
original_listed_time               0
remote_allowed                108603
job_posting_url                    0
application_url                36665
application_type                   0
expiry                             0
closed_time                   122776
formatted_experience_level     29409
skills_desc                   121410
listed_time                        0
posting_domain                 39968
sponsored                          0
work_type                          0
currency                       87776
compensation_type              87776
normalized_salary              87776
zip_code                       20872
fips                           27415
dtype: int64

In [6]:
# Only these 3 columns matter for Career Path Predictor
jobs_clean = jobs[['title', 'description', 'formatted_experience_level']].copy()

# Drop rows where title or description is missing
jobs_clean = jobs_clean.dropna(subset=['title', 'description'])

# Lowercase and strip whitespace from job titles
jobs_clean['title'] = jobs_clean['title'].str.lower().str.strip()

print(f"✅ Clean dataset: {jobs_clean.shape[0]} rows")
jobs_clean.head(3)

✅ Clean dataset: 123842 rows

,title,description,formatted_experience_level
0,marketing coordinator,Job descriptionA leading real estate firm in N...,NaN
1,mental health therapist/counselor,"At Aspen Therapy and Wellness , we are committ...",NaN
2,assitant restaurant manager,The National Exemplar is accepting application...,NaN

In [7]:
CAREER_DOMAINS = {
    "Software Engineering": [
        "software engineer", "backend engineer", "frontend engineer",
        "full stack developer", "software developer", "sde"
    ],
    "Data & AI": [
        "data scientist", "machine learning engineer", "data analyst",
        "ai engineer", "data engineer", "mlops engineer"
    ],
    "Product Management": [
        "product manager", "associate product manager", "senior product manager",
        "apm", "growth product manager"
    ],
    "Design": [
        "ux designer", "ui designer", "product designer",
        "interaction designer", "visual designer"
    ],
    "Finance": [
        "investment banker", "financial analyst", "equity research",
        "business analyst", "management consultant"
    ],
    "Marketing": [
        "marketing manager", "digital marketing", "content strategist",
        "brand manager", "growth hacker"
    ]
}

def tag_domain(title):
    title = str(title).lower()
    for domain, keywords in CAREER_DOMAINS.items():
        if any(keyword in title for keyword in keywords):
            return domain
    return "Other"

jobs_clean['domain'] = jobs_clean['title'].apply(tag_domain)

print("Domain distribution:")
print(jobs_clean['domain'].value_counts())

Domain distribution:
domain
Other                   118717
Software Engineering      1742
Data & AI                 1178
Finance                    981
Marketing                  540
Product Management         531
Design                     153
Name: count, dtype: int64

In [8]:
jobs_final = jobs_clean[jobs_clean['domain'] != 'Other'].copy()

print(f"Final dataset size: {jobs_final.shape[0]} rows")

# Save
jobs_final.to_csv("../data/processed/jobs_with_domains.csv", index=False)
print("✅ Saved to data/processed/jobs_with_domains.csv")

Final dataset size: 5125 rows
✅ Saved to data/processed/jobs_with_domains.csv

In [9]:
jobs.head(3)

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0